[Interface]
# VPN subnet 10.66.0.0/24
Address = 10.66.0.1/24 
SaveConfig = true

# Turn the host into a gateway: forward + NAT out the uplink
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -t nat -A POSTROUTING -s 10.66.0.0/24 -o wlan -j MASQUERADE
# if host has DOCKER installed we need to explicitly allow bi-direct flows between wg0 and wlan/eth
PostUp = iptables -I DOCKER-USER -i wg0 -o wlan0 -j ACCEPT
PostUp = iptables -I DOCKER-USER -i wlan0 -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o wlan0 -j MASQUERADE
PostDown = iptables -D DOCKER-USER -i wg0 -o wlan0 -j ACCEPT
PostDown = iptables -D DOCKER-USER -i wlan0 -o wg0 -j ACCEPT
ListenPort = 51820
PrivateKey = EHwtGyZeu0RVwtqNVSubHQSbOyBqLwl76myVWBj013E=

[Peer]
# Laptop
PublicKey = ZmG57/rewnVMQP1Z/SCqQ+xJ3xs3VFcg0w9R4HtJ0nA=
AllowedIPs = 10.66.0.2/32

[Peer]
# Phone
PublicKey = ALn/GQK2s36vTNSOCE3m9Acfsg3QZ4yat+8LBoZHa0w=
AllowedIPs = 10.66.0.3/32
